title: dr00py da cryptographer
description: > # this means to ignore newlines until "baseurl:"
  This page is awesome
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "anhdungdoan.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Doan Anh Dung # add your name
author-img: doan-dung.jpg # add your photo
about-author: Hello cac anh em, tui la Doan Anh Dung. Here is some crypto write-up ne\n Donate here 5610205167882-Agribank <3 # add description
social-twitter: khong_co_dau_khoi_kiem_he_he # add your Twitter handle
social-facebook: gnudnaod
social-github: AnhDungDoan # add your Github handle
social-linkedin: gnudnaod # add your Linkedin handle
social-email: khongphaidoandung@gmail.com

# Disqus
discus-identifier: gnud # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]

color_scheme: "black"